version: '3'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony_docker
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
    app:
        image: fbf053a375b6bbe0b4cd9f7be92ddec1438354b3ba0aa962aaa7ca76fdf2b066
        ports:
            - "8090:80"
volumes:
    db-data:
